spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1444;databaseName=scheduleDB;TrustServerCertificate=True
    username: sa
    password: P@ssw0rd
  jpa:
    show-sql: True
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
    root: INFO

jwt:
  secret: "a1b2C3d4E5f6G7h8I9j0KlmNOPqrsTUVWxyzABCDefghIJKLmnopQRa39fjkks9askkid4o3l3ds5lirnus9d9e0ov83kso4svx"